Repository CQCL/hugr, pull requests merged in 2025-04, with the labels that each got.

#2056 feat!: Mark all Error enums as non_exhaustive
  hugr-core/src/extension.rs
  hugr-core/src/hugr/serialize/upgrade.rs
  hugr-core/src/import.rs
  hugr-model/src/v0/ast/resolve.rs
  hugr-model/src/v0/table/mod.rs
  hugr-passes/src/lower.rs
  hugr-passes/src/non_local.rs
  hugr-passes/src/replace_types/linearize.rs
  hugr-passes/src/validation.rs
Labels: breaking-change, wait to merge

#2059 feat!: Handle CallIndirect in Dataflow Analysis
  hugr-passes/src/const_fold.rs
  hugr-passes/src/const_fold/test.rs
  hugr-passes/src/const_fold/value_handle.rs
  hugr-passes/src/dataflow.rs
  hugr-passes/src/dataflow/datalog.rs
  hugr-passes/src/dataflow/partial_value.rs
  hugr-passes/src/dataflow/results.rs
  hugr-passes/src/dataflow/test.rs
  hugr-passes/src/dataflow/value_row.rs
Labels: breaking-change, wait to merge

#2093 feat!: remove ExtensionValue
  hugr-core/src/extension.rs
  hugr-core/src/extension/resolution/extension.rs
  hugr-core/src/hugr/validate/test.rs
  hugr-core/src/std_extensions/logic.rs
  hugr-py/src/hugr/_serialization/extension.py
  hugr-py/src/hugr/ext.py
  hugr-py/src/hugr/std/_json_defs/arithmetic/conversions.json
  hugr-py/src/hugr/std/_json_defs/arithmetic/float.json
  hugr-py/src/hugr/std/_json_defs/arithmetic/float/types.json
  hugr-py/src/hugr/std/_json_defs/arithmetic/int.json
  hugr-py/src/hugr/std/_json_defs/arithmetic/int/types.json
  hugr-py/src/hugr/std/_json_defs/collections/array.json
  hugr-py/src/hugr/std/_json_defs/collections/list.json
  hugr-py/src/hugr/std/_json_defs/collections/static_array.json
  hugr-py/src/hugr/std/_json_defs/logic.json
  hugr-py/src/hugr/std/_json_defs/prelude.json
  hugr-py/src/hugr/std/_json_defs/ptr.json
  specification/schema/hugr_schema_live.json
  specification/schema/hugr_schema_strict_live.json
  specification/schema/testing_hugr_schema_live.json
  specification/schema/testing_hugr_schema_strict_live.json
  specification/std_extensions/arithmetic/conversions.json
  specification/std_extensions/arithmetic/float.json
  specification/std_extensions/arithmetic/float/types.json
  specification/std_extensions/arithmetic/int.json
  specification/std_extensions/arithmetic/int/types.json
  specification/std_extensions/collections/array.json
  specification/std_extensions/collections/list.json
  specification/std_extensions/collections/static_array.json
  specification/std_extensions/logic.json
  specification/std_extensions/prelude.json
  specification/std_extensions/ptr.json
Labels: breaking-change

#1895 feat!: ComposablePass trait allowing sequencing and validation
  hugr-passes/src/composable.rs
  hugr-passes/src/const_fold.rs
  hugr-passes/src/const_fold/test.rs
  hugr-passes/src/dead_code.rs
  hugr-passes/src/dead_funcs.rs
  hugr-passes/src/lib.rs
  hugr-passes/src/monomorphize.rs
  hugr-passes/src/replace_types.rs
  hugr-passes/src/replace_types/linearize.rs
  hugr-passes/src/untuple.rs
Labels: breaking-change, wait to merge

#2094 feat!: ReplaceTypes: allow lowering ops into a Call to a function already in the Hugr
  hugr-passes/src/replace_types.rs
  hugr-passes/src/replace_types/handlers.rs
  hugr-passes/src/replace_types/linearize.rs
Labels: breaking-change

#2115 feat: move `ArrayOpBuilder` to hugr-core
  hugr-core/src/std_extensions/collections/array.rs
  hugr-core/src/std_extensions/collections/array/op_builder.rs
  hugr-llvm/src/extension/collections/array.rs
  hugr-llvm/src/utils.rs
  hugr-llvm/src/utils/array_op_builder.rs
Labels: breaking-change

#2070 feat!: Split Rewrite trait into VerifyPatch and ApplyPatch
  hugr-core/src/hugr.rs
  hugr-core/src/hugr/hugrmut.rs
  hugr-core/src/hugr/patch.rs
  hugr-core/src/hugr/patch/consts.rs
  hugr-core/src/hugr/patch/inline_call.rs
  hugr-core/src/hugr/patch/inline_dfg.rs
  hugr-core/src/hugr/patch/insert_identity.rs
  hugr-core/src/hugr/patch/outline_cfg.rs
  hugr-core/src/hugr/patch/port_types.rs
  hugr-core/src/hugr/patch/replace.rs
  hugr-core/src/hugr/patch/simple_replace.rs
  hugr-core/src/hugr/views/sibling_subgraph.rs
  hugr-passes/src/lower.rs
  hugr-passes/src/merge_bbs.rs
  hugr-passes/src/nest_cfgs.rs
  hugr-passes/src/untuple.rs
  hugr/src/hugr.rs
Labels: breaking-change, wait to merge

#2128 chore(hugr-llvm): upgrade to inkwell 0.6.0
  Cargo.lock
  DEVELOPMENT.md
  hugr-llvm/Cargo.toml
  hugr-llvm/README.md
  hugr-llvm/src/extension/collections/static_array.rs
  hugr-llvm/src/sum.rs
  hugr-llvm/src/sum/layout.rs
Labels: dependencies, llvm
